name = "session_5_1"
uuid = "de24fe25-eafd-4693-b87d-ae291e104b24"
authors = ["Leonardo Bacciottini"]
version = "1.0.0-DEV"

[compat]
julia = "1.12.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
